### ISSUE TITLE
I have created a PKGBUILD and an AUR package

### ISSUE THREAD

**Issue by KSXGitHub** [gi-lom/gnabel#11]
I have created [a PKGBUILD](https://github.com/KSXGitHub/gnabel.pkgbuild) and [an AUR package](https://aur.archlinux.org/packages/gnabel/). I have tested the AUR package with `yay` and it works perfectly.

@jjgalvez @fushinari Do you have any criticisms?

@gi-lom Since you are the author of this project, I am willing to transfer ownership of the AUR package if you are willing to maintain it (this would only make sense if you use Arch Linux). The publication of AUR package can be automated with GitHub Workflow, I am willing to help you with that too.

**Comment by fushinari** [comment]
I'll send a PR to the Github repo

**Comment by gi-lom** [comment]
Happy to know it can be published on AUR!
I am inclined to distro hopping, so if you use Arch stably I guess it's better to leave it to you for now. But I would still like to know more about automating the publication

**Comment by KSXGitHub** [comment]
> But I would still like to know more about automating the publication

In [pretty-exec](https://github.com/KSXGitHub/pretty-exec) and [sane-fmt](https://github.com/sane-fmt/sane-fmt), I use GitHub Workflow to automate test, build, and deployment. For AUR in particular, I use Python scripts to generate PKGBUILD files and then use [KSXGitHub/github-actions-deploy-aur](https://github.com/KSXGitHub/github-actions-deploy-aur) to generate .SRCINFO and publish to the AUR.
