### ISSUE TITLE
NameError: name 'XdgConfigHome' is not defined

### ISSUE THREAD

**Issue by yochananmarqos** [gi-lom/gnabel#12]
I received this error after installing on Manjaro GNOME using my own [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/gnabel-git/PKGBUILD) building from the latest commit:

```
Traceback (most recent call last):
  File "/usr/sbin/gnabel", line 24, in <module>
    SettingsFile = os.path.join(XdgConfigHome, 'gnabel', 'settings.json')
NameError: name 'XdgConfigHome' is not defined
```

Shouldn't `~/.local/share/gnabel/settings.json` or `~/.config/gnabel/settings.json` be created if it's not found?

**Comment by KSXGitHub** [comment]
PR https://github.com/gi-lom/gnabel/pull/15

**Comment by KSXGitHub** [comment]
Anyway, `gnabel` (without `-git`) doesn't have such problem. You may use it for now.
