### ISSUE TITLE
Uninstall guide?

### ISSUE THREAD

**Issue by ashleyharvey** [gi-lom/gnabel#13]
Tried to install this on macOS, it failed, then I realized there's no uninstall process. Not sure what's been installed on my system and where. I saw `pip` pulled a few things, I guess for now I just need to go through and manually remove them.

**Comment by gi-lom** [comment]
The app is meant for use on Linux, sorry. I don't have a mac so I can't make tests, but you need to install the GTK package first: https://www.gtk.org/docs/installations/macos/

I will write an uninstall script

**Comment by gi-lom** [comment]
However, a Meson build should come soon so the install and uninstall scripts will not be permanent
