### ISSUE TITLE
Missing icons on live CD

### ISSUE THREAD

**Issue by KSXGitHub** [gi-lom/gnabel#16]
So I tried install and run gnabel on EndeavourOS Live CD, and this is the result:

![screenshot](https://user-images.githubusercontent.com/11488886/89976627-1fcc3000-dc93-11ea-9d02-eb5cc12e6dd5.png)

I am not sure which dependencies are missing as I am not familiar with GTK development.

Do you have any idea, @fushinari?

**Comment by fushinari** [comment]
Is adwaita-icon-theme installed?

**Comment by gi-lom** [comment]
What icon theme are you using?

**Comment by KSXGitHub** [comment]
The Live CD does have adwaita-icon-theme installed but not default. The default icon theme is Arc-X-D.

Anyway, booting Live CD can be a pain, so if you are determined to fix this issue, you may install EndeavourOS into a virtual machine and try it yourself.

**Comment by gi-lom** [comment]
I remember getting the same error when putting an icon theme that was incomplete, so I'm quite sure it depends on the global icon theme. What happens if you use another one (one that is well maintained, like for example Papirus)?

**Comment by fushinari** [comment]
Not a gnabel issue. gnabel does nothing non-standard in this. 

@gi-lom you can safely close this. There's nothing to fix. It's just poor defaults in a distro.
