### ISSUE TITLE
Auto-translation

### ISSUE THREAD

**Issue by KSXGitHub** [gi-lom/gnabel#18]
The Google Translate website automatically produces translated text as user type input text. The Crow Translate application also has a checkbox to enable auto-translation.

It would be great if Gnabel has the same feature.

However, I suspect that Gnabel requests for translation synchronously. If this is true, it would freeze the GUI on every character user types, leading to bad experience, so you may need to convert your mechanism to asynchronous first.

**Comment by fushinari** [comment]
GLib.idle_add() will do.
