### ISSUE TITLE
Thoughts about changing search behavior

### ISSUE THREAD

**Issue by fushinari** [gi-lom/gnabel#21]
What do you guys think about changing the search behavior? It's standard in messaging applications to use Ctrl+Enter for linebreaks and Enter for actually sending the message.

The current code for the current behavior is a dirty hack. I was rewriting some of the GTK code to make it simpler, so I came across this weird behavior and wanted to know what you all thought about it.

@gi-lom @KSXGitHub @rafaelmardojai

**Comment by rafaelmardojai** [comment]
IMO it should behave similar to Google Translate web interface. 

`Enter` for linebreaks and an automatic translation as you type (#18).

**Comment by fushinari** [comment]
> IMO it should behave similar to Google Translate web interface.
> 
> `Enter` for linebreaks and an automatic translation as you type (#18).

I'm fine with that too, but is there any possibility of issues like API abuse?

**Comment by rafaelmardojai** [comment]
I was asking me the same.

[py-googletrans](https://github.com/ssut/py-googletrans) repo says:

> Googletrans is a free and unlimited python library that implemented Google Translate API. This uses the Google Translate Ajax API to make calls to such methods as detect and translate.

And also:

> 
> ### How does this library work
> 
> You may wonder why this library works properly, whereas other approaches such like goslate won't work since Google has updated its translation service recently with a ticket mechanism to prevent a lot of crawler programs.
> 
> I eventually figure out a way to generate a ticket by reverse engineering on the obfuscated and minified code used by Google to generate such token, and implemented on the top of Python. However, this could be blocked at any time.

**Comment by fushinari** [comment]
I guess that means there's the possibility that one day we'll wake up to Gnabel not working anymore?

If we use this for live, consecutive requests, the result could be the API getting blocked permanently.

Technically, it's a very simple thing that [I already do in my project](https://github.com/fushinari/reo/blob/3f6035a6687a4de08249332760bff73dde422ab4/reo/gtk/window.py#L146). But considering the possible risk... should it be an option instead?

**Comment by rafaelmardojai** [comment]
Yeah, the default should be to manually press the translate button.

**Comment by fushinari** [comment]
There's no settings interface yet... Should I put it as an  option usable by setting an environment variable?

Thanks and I use your Firefox theme on my GNOME setup, it's great :)

**Comment by rafaelmardojai** [comment]
Yeah, LGTM.

**Comment by fushinari** [comment]
I just noticed that I made a mistake... Kinda... I've set it up so that the `Ctrl+Enter` searches and `Enter ` does linebreaks... 

@gi-lom @rafaelmardojai is that good enough?
