### ISSUE TITLE
Installing with Meson, I had to install googletrans, gtts and pydub with pip

### ISSUE THREAD

**Issue by gi-lom** [gi-lom/gnabel#23]
Is this something Meson should be able to do alone? If not, then better specify in the readme they have to be installed through pip

**Comment by fushinari** [comment]
It shouldn't be done by Meson. Meson is a build system, not a package manager. Handling dependencies is not a build system's job. The dependencies and their expected package names (should be same or similar across distros) are already listed in the README so packagers would know what dependencies to list.

A general user should only have to use the flatpak or a package from their respective repositories (for example, AUR for Arch users).

@rafaelmardojai did a great work with all of it.
