### ISSUE TITLE
HIG compliant app icon

### ISSUE THREAD

**Issue by jimmac** [gi-lom/gnabel#25]
While Gnabel ships an app icon, it would be nice to have a proper [GNOME HIG compliant](https://developer.gnome.org/hig/stable/icon-design.html.en) app icon with a symbolic variant.

**Comment by jimmac** [comment]
Might show its origins a little strongly, but here's my initial suggestion:

![image](https://user-images.githubusercontent.com/14821/90127283-39d64300-dd65-11ea-917e-127f7e559d63.png)

**Comment by gi-lom** [comment]
Made a symbolic icon
